export const EMPLOYEES_LIST_REQUEST = "EMPLOYEES_LIST_REQUEST";
export const EMPLOYEES_LIST_SUCCESS = "EMPLOYEES_LIST_SUCCESS";
export const EMPLOYEES_LIST_FAIL = "EMPLOYEES_LIST_FAIL";

export const EMPLOYEES_CREATE_REQUEST = "EMPLOYEES_CREATE_REQUEST";
export const EMPLOYEES_CREATE_SUCCESS = "EMPLOYEES_CREATE_SUCCESS";
export const EMPLOYEES_CREATE_FAIL = "EMPLOYEES_CREATE_FAIL";

export const EMPLOYEES_UPDATE_REQUEST = "EMPLOYEES_UPDATE_REQUEST";
export const EMPLOYEES_UPDATE_SUCCESS = "EMPLOYEES_UPDATE_SUCCESS";
export const EMPLOYEES_UPDATE_FAIL = "EMPLOYEES_UPDATE_FAIL";

export const EMPLOYEES_DELETE_REQUEST = "EMPLOYEES_DELETE_REQUEST";
export const EMPLOYEES_DELETE_SUCCESS = "EMPLOYEES_DELETE_SUCCESS";
export const EMPLOYEES_DELETE_FAIL = "EMPLOYEES_DELETE_FAIL";